-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg3cRtR59Ac2iH2Cv3
zN7F2Gk3daSbeIxVFf8GgVjQDkqgCgYIKoZIzj0DAQehRANCAAQkrdBebAnCMdOc
uFmvh0+kt3cFGmMQx/hNb/cqu0uWpZW0wHrjXYWazzrzrJD7Zi8k/ZMInkVweA5p
JsHWY8eg
-----END PRIVATE KEY-----